@adminAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImhzZWlubyIsImVtYWlsIjoiaHNlaW5vQGFybWVkY2l2aWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNzEwODAzMjcxLCJleHAiOjE3MTA4MTA0NzF9.jAO-sHCRk2kkKnmU51kdgOSC19CRGs8stYflXY7OVpQ
@companyAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImNvbXBhbnk0IiwiZW1haWwiOiJjb21wYW55NEBleGFtcGxlLmNvbSIsInJvbGVzIjpbImNvbXBhbnkiXSwiaWF0IjoxNzEyNTg2MDE5LCJleHAiOjE3MTI1OTMyMTl9.hPAsjbPUqwobFCzi6kpoVI3PjSy0GIhLB93gACcLrzc
@userAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImNvbXBhbnkxdXNlcjEiLCJlbWFpbCI6ImNvbXBhbnkxdXNlcjFAZXhhbXBsZS5jb20iLCJyb2xlcyI6WyJ1c2VyIl0sImlhdCI6MTcxMDI2MTQxOCwiZXhwIjoxNzEwMjY4NjE4fQ.RQacTi7_w-9oV7X-jkcpshZzBrmeKZgpOwGO7_gqXAc

###

POST http://localhost:3001/auth/admin/login HTTP/1.1
Content-Type: application/json

{
  "email": "hseino@armedcivil.com",
  "password": "adminadmin"
}

###

POST http://localhost:3001/auth/company/login HTTP/1.1
Content-Type: application/json

{
  "email": "company4@example.com",
  "password": "password"
}

###

POST http://localhost:3001/auth/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "company1user1@example.com",
  "password": "password"
}

###

GET http://localhost:3001/auth/check HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{adminAccessToken}}

###

GET http://localhost:3001/company/?page=3 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{adminAccessToken}}

###

GET http://localhost:3001/company/41 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{adminAccessToken}}

###

POST http://localhost:3001/company
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "name": "comapny80",
  "email": "company80@example.com",
  "password": "password",
  "password_confirmation": "password"
}

###

PATCH http://localhost:3001/company/1
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "id": 1,
  "name": "company1",
  "email": "company1@example.com",
  "password": "password",
  "passwordConfirmation": "password"
}

###

DELETE  http://localhost:3001/company/41
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

###

GET http://localhost:3001/company/profile HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{companyAccessToken}}

###

PATCH http://localhost:3001/company/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{companyAccessToken}}

{
  "name": "company1",
  "email": "company1@example.com"
}

###

GET http://localhost:3001/user?page=4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{companyAccessToken}}

###

GET http://localhost:3001/user/121 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{companyAccessToken}}

###

POST http://localhost:3001/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{companyAccessToken}}

{
  "name": "comapny4user42",
  "email": "comapny4user42@example.com",
  "password": "password",
  "passwordConfirmation": "password"
}

###

GET http://localhost:3001/company/floor HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{companyAccessToken}}

###

POST http://localhost:3001/company/floor HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{companyAccessToken}}

{
  "floors": [
    {
      "label" : "国王軍第３騎士団第１兵舎",
      "objects":[{"modelPath":"/models/circle-desk.glb","matrix":{"elements":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}},{"modelPath":"/models/chair.glb","matrix":{"elements":[0.021115678037200603,0,0.9997770392147588,0,0,1,0,0,-0.9997770392147588,0,0.021115678037200603,0,1.9005579413072422,0,-0.004496067233618284,1]}}]
    },

    {
      "label" : "国王軍第３騎士団第２兵舎",
      "objects":[{"modelPath":"/models/circle-desk.glb","matrix":{"elements":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}},{"modelPath":"/models/chair.glb","matrix":{"elements":[0.021115678037200603,0,0.9997770392147588,0,0,1,0,0,-0.9997770392147588,0,0.021115678037200603,0,1.9005579413072422,0,-0.004496067233618284,1]}}]
    }
  ]
}

###

GET http://localhost:3001/company/editor-asset?order=desc&page=2 HTTP/1.1
Authorization: Bearer {{companyAccessToken}}